/**
 * store.ts
 * Zustand global state — extended for AI upgrade.
 * Adds: AI classification result, AI-regenerated schema, hybrid generation metadata.
 */

import { create } from 'zustand';
import type { ParsedTable } from './api';

// ── AI Classification Result ─────────────────────────────────────────────────
export interface ClassificationResult {
  complexity: 'basic' | 'medium' | 'high' | 'domain_specific';
  detected_domain: string;
  selected_domain: string;
  recommendation: 'faker_only' | 'hybrid' | 'ai_regeneration';
  reason: string;
  ai_columns: string[];
  faker_columns: string[];
}

// ── AI Regenerated Schema ────────────────────────────────────────────────────
export interface RegeneratedSchema {
  success: boolean;
  domain: string;
  generated_schema_sql: string;
  explanation: string;
  tables: string[];
  warnings: string[];
  provider_used: string;
}

interface StoreState {
  // ── Existing (preserved) ───────────────────────────────────────────────────
  ddl: string;
  setDdl: (ddl: string) => void;

  parsedSchema: ParsedTable[] | null;
  setParsedSchema: (schema: ParsedTable[] | null) => void;

  generationOrder: string[];
  setGenerationOrder: (order: string[]) => void;

  generatedData: Record<string, Record<string, unknown>[]> | null;
  setGeneratedData: (data: Record<string, Record<string, unknown>[]> | null) => void;

  agentLog: string;
  setAgentLog: (log: string) => void;

  validationIssues: string[];
  setValidationIssues: (issues: string[]) => void;

  validationPassed: boolean;
  setValidationPassed: (passed: boolean) => void;

  schemaSummary: string;
  setSchemaSummary: (summary: string) => void;

  backendStatus: 'unknown' | 'connected' | 'disconnected';
  setBackendStatus: (status: 'unknown' | 'connected' | 'disconnected') => void;

  // ── New: AI features ───────────────────────────────────────────────────────

  /** Selected domain / use case */
  selectedDomain: string;
  setSelectedDomain: (domain: string) => void;

  /** Whether user has allowed AI to regenerate the schema */
  aiRegenerationAllowed: boolean;
  setAiRegenerationAllowed: (allowed: boolean) => void;

  /** Classification result from /api/ai/classify-schema */
  classificationResult: ClassificationResult | null;
  setClassificationResult: (result: ClassificationResult | null) => void;

  /** AI-regenerated schema (preview, not yet applied) */
  aiRegeneratedSchema: RegeneratedSchema | null;
  setAiRegeneratedSchema: (schema: RegeneratedSchema | null) => void;

  /** Whether the user confirmed to use the AI-generated schema */
  aiSchemaConfirmed: boolean;
  setAiSchemaConfirmed: (confirmed: boolean) => void;

  /** Generation mode used in the last run */
  generationModeUsed: string;
  setGenerationModeUsed: (mode: string) => void;

  /** Fields generated by Faker in last hybrid run */
  fakerGeneratedFields: string[];
  setFakerGeneratedFields: (fields: string[]) => void;

  /** Fields generated by AI in last hybrid run */
  aiGeneratedFields: string[];
  setAiGeneratedFields: (fields: string[]) => void;

  /** AI provider info */
  aiProviderName: string;
  setAiProviderName: (name: string) => void;
  aiProviderAvailable: boolean;
  setAiProviderAvailable: (available: boolean) => void;

  // ── Reset helpers ─────────────────────────────────────────────────────────

  /** Reset all AI state when user uploads a new schema */
  resetAiState: () => void;
}

export const useStore = create<StoreState>((set) => ({
  // ── Existing ───────────────────────────────────────────────────────────────
  ddl: '',
  setDdl: (ddl) => set({ ddl }),

  parsedSchema: null,
  setParsedSchema: (parsedSchema) => set({ parsedSchema }),

  generationOrder: [],
  setGenerationOrder: (generationOrder) => set({ generationOrder }),

  generatedData: null,
  setGeneratedData: (generatedData) => set({ generatedData }),

  agentLog: '',
  setAgentLog: (agentLog) => set({ agentLog }),

  validationIssues: [],
  setValidationIssues: (validationIssues) => set({ validationIssues }),

  validationPassed: false,
  setValidationPassed: (validationPassed) => set({ validationPassed }),

  schemaSummary: '',
  setSchemaSummary: (schemaSummary) => set({ schemaSummary }),

  backendStatus: 'unknown',
  setBackendStatus: (backendStatus) => set({ backendStatus }),

  // ── New AI state ──────────────────────────────────────────────────────────
  selectedDomain: '',
  setSelectedDomain: (selectedDomain) => set({ selectedDomain }),

  aiRegenerationAllowed: false,
  setAiRegenerationAllowed: (aiRegenerationAllowed) => set({ aiRegenerationAllowed }),

  classificationResult: null,
  setClassificationResult: (classificationResult) => set({ classificationResult }),

  aiRegeneratedSchema: null,
  setAiRegeneratedSchema: (aiRegeneratedSchema) => set({ aiRegeneratedSchema }),

  aiSchemaConfirmed: false,
  setAiSchemaConfirmed: (aiSchemaConfirmed) => set({ aiSchemaConfirmed }),

  generationModeUsed: 'faker_only',
  setGenerationModeUsed: (generationModeUsed) => set({ generationModeUsed }),

  fakerGeneratedFields: [],
  setFakerGeneratedFields: (fakerGeneratedFields) => set({ fakerGeneratedFields }),

  aiGeneratedFields: [],
  setAiGeneratedFields: (aiGeneratedFields) => set({ aiGeneratedFields }),

  aiProviderName: 'fallback',
  setAiProviderName: (aiProviderName) => set({ aiProviderName }),

  aiProviderAvailable: false,
  setAiProviderAvailable: (aiProviderAvailable) => set({ aiProviderAvailable }),

  resetAiState: () =>
    set({
      selectedDomain: '',
      aiRegenerationAllowed: false,
      classificationResult: null,
      aiRegeneratedSchema: null,
      aiSchemaConfirmed: false,
      generationModeUsed: 'faker_only',
      fakerGeneratedFields: [],
      aiGeneratedFields: [],
    }),
}));
