/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ValidationRouteImport } from './routes/validation'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as SchemaRouteImport } from './routes/schema'
import { Route as GeneratorRouteImport } from './routes/generator'
import { Route as ExportRouteImport } from './routes/export'
import { Route as DataRouteImport } from './routes/data'
import { Route as AiSchemaPreviewRouteImport } from './routes/ai-schema-preview'
import { Route as AiRecommendRouteImport } from './routes/ai-recommend'
import { Route as AiRouteImport } from './routes/ai'
import { Route as IndexRouteImport } from './routes/index'

const ValidationRoute = ValidationRouteImport.update({
  id: '/validation',
  path: '/validation',
  getParentRoute: () => rootRouteImport,
} as any)
const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const SchemaRoute = SchemaRouteImport.update({
  id: '/schema',
  path: '/schema',
  getParentRoute: () => rootRouteImport,
} as any)
const GeneratorRoute = GeneratorRouteImport.update({
  id: '/generator',
  path: '/generator',
  getParentRoute: () => rootRouteImport,
} as any)
const ExportRoute = ExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => rootRouteImport,
} as any)
const DataRoute = DataRouteImport.update({
  id: '/data',
  path: '/data',
  getParentRoute: () => rootRouteImport,
} as any)
const AiSchemaPreviewRoute = AiSchemaPreviewRouteImport.update({
  id: '/ai-schema-preview',
  path: '/ai-schema-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const AiRecommendRoute = AiRecommendRouteImport.update({
  id: '/ai-recommend',
  path: '/ai-recommend',
  getParentRoute: () => rootRouteImport,
} as any)
const AiRoute = AiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/ai-recommend': typeof AiRecommendRoute
  '/ai-schema-preview': typeof AiSchemaPreviewRoute
  '/data': typeof DataRoute
  '/export': typeof ExportRoute
  '/generator': typeof GeneratorRoute
  '/schema': typeof SchemaRoute
  '/upload': typeof UploadRoute
  '/validation': typeof ValidationRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/ai-recommend': typeof AiRecommendRoute
  '/ai-schema-preview': typeof AiSchemaPreviewRoute
  '/data': typeof DataRoute
  '/export': typeof ExportRoute
  '/generator': typeof GeneratorRoute
  '/schema': typeof SchemaRoute
  '/upload': typeof UploadRoute
  '/validation': typeof ValidationRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/ai-recommend': typeof AiRecommendRoute
  '/ai-schema-preview': typeof AiSchemaPreviewRoute
  '/data': typeof DataRoute
  '/export': typeof ExportRoute
  '/generator': typeof GeneratorRoute
  '/schema': typeof SchemaRoute
  '/upload': typeof UploadRoute
  '/validation': typeof ValidationRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai'
    | '/ai-recommend'
    | '/ai-schema-preview'
    | '/data'
    | '/export'
    | '/generator'
    | '/schema'
    | '/upload'
    | '/validation'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai'
    | '/ai-recommend'
    | '/ai-schema-preview'
    | '/data'
    | '/export'
    | '/generator'
    | '/schema'
    | '/upload'
    | '/validation'
  id:
    | '__root__'
    | '/'
    | '/ai'
    | '/ai-recommend'
    | '/ai-schema-preview'
    | '/data'
    | '/export'
    | '/generator'
    | '/schema'
    | '/upload'
    | '/validation'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiRoute: typeof AiRoute
  AiRecommendRoute: typeof AiRecommendRoute
  AiSchemaPreviewRoute: typeof AiSchemaPreviewRoute
  DataRoute: typeof DataRoute
  ExportRoute: typeof ExportRoute
  GeneratorRoute: typeof GeneratorRoute
  SchemaRoute: typeof SchemaRoute
  UploadRoute: typeof UploadRoute
  ValidationRoute: typeof ValidationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/validation': {
      id: '/validation'
      path: '/validation'
      fullPath: '/validation'
      preLoaderRoute: typeof ValidationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schema': {
      id: '/schema'
      path: '/schema'
      fullPath: '/schema'
      preLoaderRoute: typeof SchemaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/generator': {
      id: '/generator'
      path: '/generator'
      fullPath: '/generator'
      preLoaderRoute: typeof GeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/export': {
      id: '/export'
      path: '/export'
      fullPath: '/export'
      preLoaderRoute: typeof ExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data': {
      id: '/data'
      path: '/data'
      fullPath: '/data'
      preLoaderRoute: typeof DataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-schema-preview': {
      id: '/ai-schema-preview'
      path: '/ai-schema-preview'
      fullPath: '/ai-schema-preview'
      preLoaderRoute: typeof AiSchemaPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-recommend': {
      id: '/ai-recommend'
      path: '/ai-recommend'
      fullPath: '/ai-recommend'
      preLoaderRoute: typeof AiRecommendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai': {
      id: '/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiRoute: AiRoute,
  AiRecommendRoute: AiRecommendRoute,
  AiSchemaPreviewRoute: AiSchemaPreviewRoute,
  DataRoute: DataRoute,
  ExportRoute: ExportRoute,
  GeneratorRoute: GeneratorRoute,
  SchemaRoute: SchemaRoute,
  UploadRoute: UploadRoute,
  ValidationRoute: ValidationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
