"""
exporters.py
------------
Handles all output generation:
  - CSV files (one per table) via pandas
  - SQL INSERT statements (one combined .sql file)
  - Markdown generation report

All outputs are written to a specified output directory.
"""

import os
import io
import zipfile
from typing import Dict, List, Any
from datetime import datetime
import pandas as pd
from src.schema_models import SchemaModel


def export_csv_files(
    all_data: Dict[str, List[Dict[str, Any]]],
    output_dir: str,
) -> Dict[str, str]:
    """
    Write one CSV file per table into output_dir/csv/.
    Returns a dict of {table_name: file_path}.
    """
    csv_dir = os.path.join(output_dir, "csv")
    os.makedirs(csv_dir, exist_ok=True)

    paths: Dict[str, str] = {}
    for table_name, rows in all_data.items():
        if not rows:
            continue
        df = pd.DataFrame(rows)
        path = os.path.join(csv_dir, f"{table_name}.csv")
        df.to_csv(path, index=False)
        paths[table_name] = path

    return paths


def get_csv_bytes(all_data: Dict[str, List[Dict[str, Any]]]) -> Dict[str, bytes]:
    """Return CSV content as bytes dict (used by Streamlit download buttons)."""
    result: Dict[str, bytes] = {}
    for table_name, rows in all_data.items():
        if not rows:
            continue
        df = pd.DataFrame(rows)
        buf = io.StringIO()
        df.to_csv(buf, index=False)
        result[table_name] = buf.getvalue().encode("utf-8")
    return result


def get_csv_zip_bytes(all_data: Dict[str, List[Dict[str, Any]]]) -> bytes:
    """Return a ZIP archive of all CSV files as bytes (for Streamlit download)."""
    zip_buf = io.BytesIO()
    with zipfile.ZipFile(zip_buf, "w", zipfile.ZIP_DEFLATED) as zf:
        for table_name, rows in all_data.items():
            if not rows:
                continue
            df = pd.DataFrame(rows)
            csv_buf = io.StringIO()
            df.to_csv(csv_buf, index=False)
            zf.writestr(f"{table_name}.csv", csv_buf.getvalue())
    return zip_buf.getvalue()


def _escape_sql_value(val: Any) -> str:
    """Format a Python value as a SQL literal."""
    if val is None:
        return "NULL"
    if isinstance(val, bool):
        return "1" if val else "0"
    if isinstance(val, (int, float)):
        return str(val)
    # String: escape single quotes
    escaped = str(val).replace("'", "''")
    return f"'{escaped}'"


def export_sql_inserts(
    schema: SchemaModel,
    all_data: Dict[str, List[Dict[str, Any]]],
    generation_order: List[str],
    output_path: str,
) -> str:
    """
    Write SQL INSERT statements for all tables to output_path.
    Returns the SQL content as a string.
    """
    lines = [
        "-- ============================================================",
        "-- Generated by Schema-Aware Test Data Generator",
        f"-- Timestamp: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
        "-- ============================================================",
        "",
    ]

    for tname in generation_order:
        rows = all_data.get(tname, [])
        table = schema.get_table(tname)
        if not rows or table is None:
            continue

        col_names = [col.name for col in table.columns]
        col_list = ", ".join(col_names)

        lines.append(f"-- Table: {tname}")
        lines.append(f"INSERT INTO {tname} ({col_list}) VALUES")

        value_rows = []
        for row in rows:
            vals = [_escape_sql_value(row.get(c)) for c in col_names]
            value_rows.append(f"  ({', '.join(vals)})")

        lines.append(",\n".join(value_rows) + ";")
        lines.append("")

    sql_content = "\n".join(lines)
    os.makedirs(os.path.dirname(output_path) or ".", exist_ok=True)
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(sql_content)

    return sql_content


def get_sql_bytes(
    schema: SchemaModel,
    all_data: Dict[str, List[Dict[str, Any]]],
    generation_order: List[str],
) -> bytes:
    """Return SQL INSERT content as bytes (for Streamlit download button)."""
    lines = [
        "-- ============================================================",
        "-- Generated by Schema-Aware Test Data Generator",
        f"-- Timestamp: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
        "-- ============================================================",
        "",
    ]

    for tname in generation_order:
        rows = all_data.get(tname, [])
        table = schema.get_table(tname)
        if not rows or table is None:
            continue

        col_names = [col.name for col in table.columns]
        col_list = ", ".join(col_names)

        lines.append(f"-- Table: {tname}")
        lines.append(f"INSERT INTO {tname} ({col_list}) VALUES")

        value_rows = []
        for row in rows:
            vals = [_escape_sql_value(row.get(c)) for c in col_names]
            value_rows.append(f"  ({', '.join(vals)})")

        lines.append(",\n".join(value_rows) + ";")
        lines.append("")

    return "\n".join(lines).encode("utf-8")


def export_report(
    schema: SchemaModel,
    all_data: Dict[str, List[Dict[str, Any]]],
    generation_order: List[str],
    validation_passed: bool,
    validation_issues: List[str],
    agent_log: str,
    output_path: str,
) -> str:
    """
    Write a Markdown generation report to output_path.
    Returns the report content as a string.
    """
    ts = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    lines = [
        "# Schema-Aware Test Data Generator — Generation Report",
        f"\n**Generated:** {ts}\n",
        "---",
        "",
        "## 1. Tables Detected",
        "",
    ]

    for tname, table in schema.tables.items():
        pks = ", ".join(table.get_primary_keys()) or "none"
        fks = ", ".join(str(fk) for fk in table.foreign_keys) or "none"
        lines.append(f"### `{tname}`")
        lines.append(f"- **Columns ({len(table.columns)}):** "
                     f"{', '.join(c.name for c in table.columns)}")
        lines.append(f"- **Primary Keys:** {pks}")
        lines.append(f"- **Foreign Keys:** {fks}")
        lines.append(f"- **Rows Generated:** {len(all_data.get(tname, []))}")
        lines.append("")

    lines += [
        "---",
        "",
        "## 2. Generation Order",
        "",
        " -> ".join(generation_order),
        "",
        "---",
        "",
        "## 3. Validation Result",
        "",
    ]

    if validation_passed:
        lines.append("✅ **All validation checks PASSED.**")
    else:
        lines.append(f"⚠️ **{len(validation_issues)} validation issue(s) detected:**")
        for issue in validation_issues:
            lines.append(f"- {issue}")

    lines += [
        "",
        "---",
        "",
        "## 4. Agent Loop Log",
        "",
        "```",
        agent_log,
        "```",
        "",
        "---",
        "",
        "## 5. Assumptions & Limitations",
        "",
        "- Supports common SQL DDL patterns only (MySQL/SQLite/PostgreSQL-style).",
        "- Composite primary keys are partially supported.",
        "- Cyclic foreign key relationships are NOT supported.",
        "- Complex CHECK constraints, triggers, and stored procedures are out of scope.",
        "- NULL probability is fixed at ~12% for nullable columns.",
        "- Data is synthetic — not suitable for production use.",
        "",
        "---",
        "*Generated by Schema-Aware Test Data Generator — Infinite Computer Solutions Tech Challenge*",
    ]

    report_content = "\n".join(lines)
    os.makedirs(os.path.dirname(output_path) or ".", exist_ok=True)
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(report_content)

    return report_content


def get_report_bytes(
    schema: SchemaModel,
    all_data: Dict[str, List[Dict[str, Any]]],
    generation_order: List[str],
    validation_passed: bool,
    validation_issues: List[str],
    agent_log: str,
) -> bytes:
    """Return the report as bytes (for Streamlit download button)."""
    content = export_report(
        schema, all_data, generation_order,
        validation_passed, validation_issues, agent_log,
        output_path="/dev/null" if os.name != "nt" else "NUL",
    )
    return content.encode("utf-8")
